name: flutter_firebase_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  firebase_core: ^3.12.1
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.1
  flutter_facebook_auth: ^7.1.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  flutter_svg: ^2.0.9
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  video_player: ^2.9.3
  path_provider: ^2.1.1
  open_file: ^3.5.10
  pdf: ^3.11.3
  printing: ^5.14.2
  mobile_scanner: ^6.0.7
  share_plus: ^10.1.4
  webview_flutter: ^4.10.0
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
